---
# https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/
- name: Install NewRelic Infrastructure Agent
  block:
    - name: Install NewRelic Infrastructure repository
      template:
        src: newrelic-infra.repo.j2
        dest: /etc/yum.repos.d/newrelic-infra.repo
        owner: root
        group: root
        mode: 0644

    - name: Install newrelic-infra package
      package:
        name: newrelic-infra
        state: present

    - name: Configure newrelic-infra license key
      copy:
        content: "license_key: {{ newrelic_infra_license }}\n"
        dest: /etc/newrelic-infra.yml
        owner: root
        group: root
        mode: 0644
      notify:
        - restart newrelic-infra

    - name: Start newrelic-infra.service
      service:
        name: newrelic-infra
        state: "{{ 'started' if newrelic_infra_enabled else 'stopped' }}"
        enabled: "{{ newrelic_infra_enabled }}"

# https://docs.newrelic.com/docs/agents/php-agent/getting-started/introduction-new-relic-php#installation
- name: Install NewRelic APM Agent
  block:
    - name: Install NewRelic RPM GPG Key
      copy:
        src: RPM-GPG-KEY-NewRelic
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-NewRelic
        owner: root
        group: root
        mode: 0644

    - name: Import NewRelic RPM GPG Key
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-NewRelic
        state: present

    - name: Install NewRelic APM repository
      package:
        name: https://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm
        state: present

    - name: Install newrelic-php5 package
      package:
        name: newrelic-php5
        state: present

    - name: Configure newrelic php integration
      template:
        src: newrelic.ini.j2
        dest: /etc/php.d/newrelic.ini
        owner: root
        group: root
        mode: 0644
      notify:
        - restart newrelic-daemon
        - restart php-fpm

    - name: Configure newrelic-daemon
      template:
        src: newrelic.cfg.j2
        dest: /etc/newrelic/newrelic.cfg
        owner: root
        group: root
        mode: 0644
      notify:
        - restart newrelic-daemon
        - restart php-fpm

    - name: Start newrelic-daemon.service
      service:
        name: newrelic-daemon
        state: "{{ 'started' if newrelic_apm_enabled else 'stopped' }}"
        enabled: "{{ newrelic_apm_enabled }}"
