---
- name: restart newrelic-sysmond
  service: name=newrelic-sysmond state=restarted

- name: restart newrelic-daemon
  service: name=newrelic-daemon state=restarted

- name: restart php-fpm
  service: name=php-fpm state=restarted
