---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Ensure dependencies are installed
      package:
        name:
          - php-fpm
        state: present

  roles:
    - role: davidalger.newrelic
